In [1]:
List = ['Delhi','Mumbai','Bangalore']
List

['Delhi', 'Mumbai', 'Bangalore']

In [2]:
List.pop(2)

'Bangalore'

In [3]:
List.remove('Mumbai')

In [5]:
List

['Delhi']

In [7]:
Dict1 = {'a':'alpha','b':'beta','c':'gamma'}
Dict1

{'a': 'alpha', 'b': 'beta', 'c': 'gamma'}

In [11]:
list(Dict1.items())

[('a', 'alpha'), ('b', 'beta'), ('c', 'gamma')]

In [18]:
Dict1 = {'a':'alpha','b':'beta','c':'gamma'}
Dict1

{'a': 'alpha', 'b': 'beta', 'c': 'gamma'}

In [21]:

List=[]

for keys in Dict1.keys():
    List.append(keys)
    List.append(Dict1[keys])
List
    

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [22]:
List = []
for keys,values in Dict1.items():
    List.append(keys)
    List.append(values)
List

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [23]:
import numpy as np

In [27]:
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [29]:
a[::-1,::-1]

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [30]:
a[::-1]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [33]:
a1=np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a1.mean()

5.0

In [35]:
a1.mean(0) #vertical mean

array([4., 5., 6.])

In [36]:
a1.mean(1) #horizontal mean

array([2., 5., 8.])

In [39]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
C = np.array([True,False,True,False])
A
B
C

array([ True, False,  True, False])

In [40]:
np.where(C,A,B)

array([  1, 200,   3, 400])

In [49]:
a2 = np.random.randint(1,100,10)
a2

array([40,  1, 93, 38, 40, 20, 17, 36, 45, 91])

In [51]:
np.where(a2<40)

(array([1, 3, 5, 6, 7], dtype=int64),)

In [54]:
import pandas as pd
from pandas import Series,DataFrame

In [57]:
ser = pd.Series(['India','Bhutan','Nepal'],index=[1,5,10])

In [58]:
ser

1      India
5     Bhutan
10     Nepal
dtype: object

In [61]:
ser.reindex(range(15))

0        NaN
1      India
2        NaN
3        NaN
4        NaN
5     Bhutan
6        NaN
7        NaN
8        NaN
9        NaN
10     Nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [62]:
ser.reindex(range(15),method='ffill')

0        NaN
1      India
2      India
3      India
4      India
5     Bhutan
6     Bhutan
7     Bhutan
8     Bhutan
9     Bhutan
10     Nepal
11     Nepal
12     Nepal
13     Nepal
14     Nepal
dtype: object

In [63]:
ser.reindex(range(15),method='bfill')

0      India
1      India
2     Bhutan
3     Bhutan
4     Bhutan
5     Bhutan
6      Nepal
7      Nepal
8      Nepal
9      Nepal
10     Nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [64]:
ser.reindex(range(15),method='nearest')

0      India
1      India
2      India
3     Bhutan
4     Bhutan
5     Bhutan
6     Bhutan
7     Bhutan
8      Nepal
9      Nepal
10     Nepal
11     Nepal
12     Nepal
13     Nepal
14     Nepal
dtype: object

In [68]:
s = ser.reindex(range(15))
s

0        NaN
1      India
2        NaN
3        NaN
4        NaN
5     Bhutan
6        NaN
7        NaN
8        NaN
9        NaN
10     Nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [69]:
s.fillna('Pak')

0        Pak
1      India
2        Pak
3        Pak
4        Pak
5     Bhutan
6        Pak
7        Pak
8        Pak
9        Pak
10     Nepal
11       Pak
12       Pak
13       Pak
14       Pak
dtype: object

In [70]:
s.fillna(method='bfill')

0      India
1      India
2     Bhutan
3     Bhutan
4     Bhutan
5     Bhutan
6      Nepal
7      Nepal
8      Nepal
9      Nepal
10     Nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object